"""This script contains tools to add LED commands to a GCode file, using the M150 command specified for the LED gantry."""

import colorsys
import xml.etree.ElementTree as ET

from pathlib import Path

from gcode_parser import GCodeParser

import click
from PIL import ImageColor  # For handling named colors
import re


def generate_gcode_command(r, g, b, brightness):
    return f"M150 R{r} G{g} B{b} I{brightness} P{1}\n"


def hsv_to_rgb(h, s, v):
    # Convert HSV to RGB
    r, g, b = colorsys.hsv_to_rgb(h / 360, s / 100, v / 100)
    r = int(r * 255)
    g = int(g * 255)
    b = int(b * 255)
    return r, g, b


@click.group()
def cli():
    pass


@cli.command()
@click.argument("gcode", type=click.Path(exists=True))
@click.option(
    "-n",
    "--num-cycles",
    type=int,
    default=1,
    help="Number of cycles for the rainbow pattern",
)
@click.option(
    "-b",
    "--brightness",
    type=int,
    default=30,
)
@click.option(
    "-o",
    "--output",
    type=click.Path(),
    default=None,
    help="Output GCode file. If not specified, the output file will be named <input_gcode>_rainbow.gcode",
)
def rainbow(gcode, num_cycles, brightness, output):
    """Add a rainbow pattern to the LED gantry."""

    gcode = Path(gcode)
    # Prepare the output file
    if output is None:
        output = f"output_gcodes/{gcode.stem}_rainbow.optgcode"
    output = Path(output)

    # Read the gcode file
    gcode_path = Path(gcode)
    gcode_content = gcode_path.read_text()

    # Split the gcode content into lines
    gcode_lines = gcode_content.split("\n")

    # The rainbow pattern is generated by sweeping the Hue from 0 to 360 degrees
    saturation = 100
    value = 100

    # Constrain brightness to 0-100
    brightness = max(0, min(brightness, 100))

    gcode_parser = GCodeParser()

    gcode_output = []

    # Count number of G0/G1 commands
    num_commands = 0
    for line in gcode_lines:
        # If a line is empty or a comment, write it to the output file and skip to the next line
        if not line.strip() or line.strip().startswith(";"):
            gcode_output.append(line)
            continue

        # Extract the command and parameters from the line.
        command = gcode_parser._extract_command(line)
        params = gcode_parser._extract_params(line)

        if command in ["G0", "G1"]:
            num_commands += 1

    num_cycles = 1
    prev_hue = 0
    for i, line in enumerate(gcode_lines):

        # If a line is empty or a comment, write it to the output file and skip to the next line
        if not line.strip() or line.strip().startswith(";"):
            gcode_output.append(line)
            continue

        # Extract the command and parameters from the line.
        command = gcode_parser._extract_command(line)
        params = gcode_parser._extract_params(line)

        # Calculate the hue
        hue = int((i / num_commands) * 360 * num_cycles)

        # Only add a GCode command for hue if it changes by at least 1 degree
        if hue != prev_hue:
            # Convert the RGB color to GCode
            r, g, b = hsv_to_rgb(hue, saturation, value)

            gcode_command = generate_gcode_command(r, g, b, brightness)

            # Add the GCode command to the GCode content
            gcode_output.append(gcode_command)

            prev_hue = hue

        # Add the original GCode line to the GCode content
        gcode_output.append(line)

    # Write the GCode content to a new file
    output.write_text("\n".join(gcode_output))

    click.secho(f"Generated LED GCode: {output}", fg="green")


def _extract_paths_with_fill(svg_file):
    tree = ET.parse(svg_file)
    root = tree.getroot()

    # Namespace handling (SVGs often have namespaces)
    namespaces = {"svg": "http://www.w3.org/2000/svg"}  # Adjust if needed

    paths = []
    for elem in root.findall(".//svg:path", namespaces):
        path_data = elem.attrib.get("d", None)
        fill_color = elem.attrib.get("fill", None)  # Extract fill if present
        paths.append({"d": path_data, "fill": fill_color})

    return paths


def _fill_to_rgb(fill_color):
    """Convert an SVG fill color to RGB.

    Args:
        fill_color (str): The fill color in SVG format.

    Returns:
        tuple: The RGB color as a tuple (r, g, b).
    """
    # If no fill provided or 'none', default to white
    if not fill_color or fill_color.lower() == "none":
        return (255, 255, 255)

    try:
        # Handle hex colors like #RRGGBB or #RGB
        if fill_color.startswith("#"):
            return ImageColor.getrgb(fill_color)

        # Handle rgb(r, g, b) format
        rgb_match = re.match(r"rgb\(\s*(\d+),\s*(\d+),\s*(\d+)\s*\)", fill_color)
        if rgb_match:
            return tuple(map(int, rgb_match.groups()))

        # Handle color names (e.g., "red", "blue")
        return ImageColor.getrgb(fill_color)

    except ValueError:
        # Default to white if parsing fails
        return (255, 255, 255)


@cli.command()
@click.argument("gcode", type=click.Path(exists=True))
@click.option(
    "--svg",
    type=click.Path(exists=True),
    help="SVG file associated with the GCode",
    default=None,
)
def svg_color(gcode, svg):
    """Extracts colors from the SVG file associated with the gcode."""

    if svg is None:
        # Assume the SVG file has the same name as the GCode file
        svg = gcode.replace(".gcode", ".svg")

        # Check if the SVG file exists
        if not Path(svg).exists():
            click.secho(f"SVG file not found: {svg}", fg="red")
            return

    # Read the SVG file
    svg_path = Path(svg)
    svg_paths = _extract_paths_with_fill(svg_path)

    print(f"Extracted {len(svg_paths)} paths from {svg_path}")

    fill_colors = [_fill_to_rgb(path["fill"]) for path in svg_paths]

    # Read the gcode file
    gcode_path = Path(gcode)
    gcode_content = gcode_path.read_text()

    # Split the gcode content into lines
    gcode_lines = gcode_content.split("\n")

    gcode_parser = GCodeParser()

    gcode_output = []

    # Count number of G0 commands
    num_commands = 0
    for line in gcode_lines:
        # If a line is empty or a comment, write it to the output file and skip to the next line
        if not line.strip() or line.strip().startswith(";"):
            gcode_output.append(line)
            continue

        # Extract the command and parameters from the line.
        command = gcode_parser._extract_command(line)
        params = gcode_parser._extract_params(line)

        if command == "G0":
            num_commands += 1

    print(f"Found {num_commands} G0 commands in {gcode_path}")

    # Confirm that the number of G0 commands and fill colors match
    # It is possible that there is one more G0 command than fill color, this is okay
    if not (num_commands == len(fill_colors) or num_commands == len(fill_colors) + 1):
        click.secho(
            f"Number of G0 commands ({num_commands}) does not match number of fill colors ({len(fill_colors)})",
            fg="red",
        )
        return

    # Add the fill colors to the GCode
    gcode_output = []
    for i, line in enumerate(gcode_lines):

        # If a line is empty or a comment, write it to the output file and skip to the next line
        if not line.strip() or line.strip().startswith(";"):
            gcode_output.append(line)
            continue

        # Extract the command and parameters from the line.
        command = gcode_parser._extract_command(line)
        params = gcode_parser._extract_params(line)

        if command == "G0" and fill_colors:
            fill_color = fill_colors.pop(0)
            r, g, b = fill_color

            gcode_command = generate_gcode_command(r, g, b, 100)

            # First add G0
            gcode_output.append(line)

            # Add the GCode command to the GCode content
            gcode_output.append(gcode_command)

        else:
            # Add the original GCode line to the GCode content
            gcode_output.append(line)

    # Write the GCode content to a new file
    output = f"output_gcodes/{gcode_path.stem}_color.optgcode"
    output_path = Path(output)
    output_path.write_text("\n".join(gcode_output))

    click.secho(f"Generated LED GCode: {output_path}", fg="green")


if __name__ == "__main__":
    cli()
