import colorsys
from pathlib import Path

import click


def generate_gcode_command(r, g, b, brightness):
    return f"M150 R{r} G{g} B{b} I{brightness} P{1}\n"


def hsv_to_rgb(h, s, v):
    # Convert HSV to RGB
    r, g, b = colorsys.hsv_to_rgb(h / 360, s / 100, v / 100)
    r = int(r * 255)
    g = int(g * 255)
    b = int(b * 255)
    return r, g, b


def is_G0(line):
    return line.startswith("G0")


@click.command()
@click.argument("gcode", type=click.Path(exists=True))
def main(gcode):
    # Read the gcode file
    gcode_path = Path(gcode)
    gcode_content = gcode_path.read_text()

    # Split the gcode content into lines
    gcode_lines = gcode_content.split("\n")

    # The goal is to sweep the LED in a rainbow pattern over the course of the GCode
    # Stepping away from the GCode, how do we generate a rainbow pattern?
    # We can use the HSV color space to generate a rainbow pattern
    # We can then convert the HSV color to RGB
    # We can then convert the RGB color to GCode

    # The HSV color space is a cylindrical coordinate representation of RGB color space
    # H: Hue, S: Saturation, V: Value
    # Hue is the color type, represented as a degree on the color wheel
    # Saturation is the intensity of the color, represented as a percentage
    # Value is the brightness of the color, represented as a percentage

    # The rainbow pattern is generated by sweeping the Hue from 0 to 360 degrees

    saturation = 100
    value = 100

    gcode_output = []

    num_cycles = 1
    prev_hue = 0
    for i, line in enumerate(gcode_lines):
        if is_G0(line):
            # Turn off LED, add G1, turn on LED
            gcode_output.append("M150 R0 U0 B0 P0")
            # Replace G0 with G1
            line = line.replace("G0", "G1")

            gcode_output.append(line)

            # Add prev_hue to the GCode content
            if prev_hue != -1:
                r, g, b = hsv_to_rgb(prev_hue, saturation, value)
                brightness = 100
                gcode_command = generate_gcode_command(r, g, b, brightness)

                gcode_output.append(gcode_command)

        else:
            # Calculate the hue
            hue = int((i / len(gcode_lines)) * 360 * num_cycles)

            # Only add a GCode command for hue if it changes by at least 1 degree
            if hue != prev_hue:
                # Convert the RGB color to GCode
                r, g, b = hsv_to_rgb(hue, saturation, value)
                brightness = 100
                gcode_command = generate_gcode_command(r, g, b, brightness)

                # Add the GCode command to the GCode content
                gcode_output.append(gcode_command)

                prev_hue = hue

            # Add the original GCode line to the GCode content
            gcode_output.append(line)

    # Write the GCode content to a new file
    output_gcode_path = gcode_path.with_name(f"{gcode_path.stem}_led.gcode")
    output_gcode_path.write_text("\n".join(gcode_output))

    click.secho(f"Generated LED GCode: {output_gcode_path}", fg="green")


if __name__ == "__main__":
    main()
